version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_NAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
      MONGO_USER: $LYRA_DB_USER
      MONGO_DB: $LYRA_DB_NAME
      MONGO_PASSWORD: $LYRA_DB_PASSWORD
    volumes:
      - ~/.lyra/db:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

  noded:
    image: wizdy/lyranoded:3.5.0.9
    restart: always
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: $HTTPS_CERT_PASSWORD
      ASPNETCORE_Kestrel__Certificates__Default__Path: /root/.lyra/https/${HTTPS_CERT_NAME}.pfx
      LYRA_POS_WALLET_NAME: ${LYRA_POS_WALLET_NAME}
      LYRA_POS_WALLET_PASSWORD: ${LYRA_POS_WALLET_PASSWORD}
      LYRA_NETWORK: ${LYRA_NETWORK}
      LYRA_DB_NAME: ${LYRA_DB_NAME}
      LYRA_DB_USER: ${LYRA_DB_USER}
      LYRA_DB_PASSWORD: ${LYRA_DB_PASSWORD}
      LYRA_P2P_PORT: ${LYRA_P2P_PORT}
      LYRA_API_PORT: ${LYRA_API_PORT}
      ASPNETCORE_URLS: https://*:${LYRA_API_PORT}
      ASPNETCORE_HTTPS_PORT: ${LYRA_API_PORT}
      LYRA_ApplicationConfiguration__P2P__Port: ${LYRA_P2P_PORT}
      LYRA_ApplicationConfiguration__P2P__Endpoint: ${LYRA_API_ENDPOINT}
      LYRA_ApplicationConfiguration__LyraNode__Lyra__Mode: $LYRA_NODE_MODE
      LYRA_ApplicationConfiguration__LyraNode__Lyra__Database__DBConnect: mongodb://${LYRA_DB_USER}:${LYRA_DB_PASSWORD}@mongo
      LYRA_ApplicationConfiguration__LyraNode__Lyra__Wallet__Name: ${LYRA_POS_WALLET_NAME}
      LYRA_ApplicationConfiguration__LyraNode__Lyra__Wallet__Password: ${LYRA_POS_WALLET_PASSWORD}
    ports:
      - ${LYRA_P2P_PORT}:${LYRA_P2P_PORT}
      - ${LYRA_API_PORT}:${LYRA_API_PORT}
      - 443:${LYRA_API_PORT}
    volumes:
      - ~/.lyra:/root/.lyra
    depends_on:
      - mongo

volumes:
  .lyra: null
