version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_NAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
      MONGO_USER: $LYRA_DB_USER
      MONGO_DB: $LYRA_DB_NAME
      MONGO_PASSWORD: $LYRA_DB_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - ~/lyradb:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

  noded:
    image: wizdy/lyranoded:0.0.6
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: $HTTPS_CERT_PASSWORD
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/${HTTPS_CERT_NAME}.pfx
      LYRA_POS_WALLET_NAME: ${LYRA_POS_WALLET_NAME}
      LYRA_POS_WALLET_PASSWORD: ${LYRA_POS_WALLET_PASSWORD}
      LYRA_NETWORK: ${LYRA_NETWORK}
      LYRA_DB_NAME: ${LYRA_DB_NAME}
      LYRA_DB_USER: ${LYRA_DB_USER}
      LYRA_DB_PASSWORD: ${LYRA_DB_PASSWORD}
      LYRA_P2P_PORT: ${LYRA_P2P_PORT}
      LYRA_API_PORT: ${LYRA_API_PORT}
      ASPNETCORE_URLS: http://*:${LYRA_P2P_PORT};https://*:${LYRA_API_PORT}
      ASPNETCORE_HTTPS_PORT: ${LYRA_API_PORT}
      LYRA_ApplicationConfiguration__LyraNode__Lyra__Database__DBConnect: mongodb://${LYRA_DB_USER}:${LYRA_DB_PASSWORD}@127.0.0.1/${LYRA_DB_NAME}
      LYRA_ApplicationConfiguration__LyraNode__Lyra__Wallet__Name: ${LYRA_POS_WALLET_NAME}
      LYRA_ApplicationConfiguration__LyraNode__Lyra__Wallet__Password: ${LYRA_POS_WALLET_PASSWORD}
    ports:
      - 4505:4505
      - 4504:4504
      - 5505:5505
      - 5504:5504
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - mongo

volumes:
  db: