version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

      MONGO_USER: $LYRA_DB_USER
      MONGO_DB: $LYRA_DB_NAME
      MONGO_PASSWORD: $LYRA_DB_PASSWORD
    networks:
      - app
    volumes:
      - db:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

  bash:
    image: bash
    entrypoint: sleep 100000000
    networks:
      - app

networks:
  app:

volumes:
  db: