using System;
using System.Collections.Generic;
using System.Text;

namespace LyraWallet.Lib
{
	// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
	public static class IconFont
	{
		public const string BriefcaseCheck = "\U000f00d7";
	}
}
